language: node_js

notifications:
  email:
    on_success: always
    on_failure: always

branches:
  only:
  - master
  - development
  - /\d+\.\d+\.\d+/

install:
  - npm install

deploy:
  provider: npm
  email: $npm_email
  api_key: $npm_apikey
  on:
    repo: ibm-bluemix-mobile-services/bms-mca-token-validation-strategy
    branch: master
    tags: true
